name: .Build directory.kpi.ua project

env:
  project: 'directory-kpi-ua'
  tag: ${{ github.sha }}
  tag-latest: 'latest'
  docker-registry-url: 'docker.pkg.github.com/kpi-ua/directory.kpi.ua/'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages & build project
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        run: |
          cd src
          npm install -g grunt-cli
          npm install grunt --save-dev
          grunt build
          grunt publish
