name: .Build directory.kpi.ua project

env:
  project: 'directory-kpi-ua'
  tag: ${{ github.sha }}
  tag-latest: 'latest'
  docker-registry-url: 'docker.pkg.github.com/kpi-ua/directory.kpi.ua/'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install packages & tools
        run: |
          cd ./src
          npm install
          npm install -g bower grunt-cli
          bower install
          
      - name: Install packages & build Docker image
        run: |
          cd ./src
          grunt build

      - name: Build Docker image
        run: |
          mv ./src/dist ./docker/
          docker build ./docker --file ./docker/Dockerfile --tag ${{ env.project }}:${{ env.tag-latest }}
          docker build -t ${{ env.project }}:${{ env.tag }} -f ./docker/Dockerfile .
          docker build -t ${{ env.project }}:${{ env.tag-latest }} -f ./docker/Dockerfile .

      - name: Docker Auth
        run: docker login -u ${{ secrets.GH_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

      - name: Push the Docker image (release tag)
        run: |
          docker tag ${{ env.project }}:${{ env.tag }} ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag }}
          docker push ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag }}

      - name: Push the Docker image (latest tag)
        run: |
          docker tag ${{ env.project }}:${{ env.tag-latest }} ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag-latest }}
          docker push ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag-latest }}


