name: .Build directory.kpi.ua project

env:
  project: 'directory-kpi-ua'
  tag: ${{ github.sha }}
  tag-latest: 'latest'
  docker-registry-url: 'docker.pkg.github.com/kpi-ua/directory.kpi.ua/'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install packages & build project
        run: |
          cd src
          npm install
          npm install -g bower grunt-cli
          bower install
          grunt build
          grunt publish
