name: .Build directory.kpi.ua project

env:
  project: 'directory-kpi-ua'
  tag: ${{ github.sha }}
  tag-latest: 'latest'
  docker-registry-url: 'docker.pkg.github.com/kpi-ua/directory.kpi.ua/'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd ./src

      - name: Install NPM packages
        run: npm install

      - name: Install Grunt cli
        run: npm install -g grunt-cli

      - name: Build via Grunt cli
        run: grunt build

      - name: Publish via Grunt cli
        run: grunt publish
